namespace TrackmaniaExchangeAPI.Models
{
    // Pulled from https://trackmania.exchange/api/tags/gettags on 08/09/24
    public enum MapTag : int
    {
        Race = 1,
        FullSpeed = 2,
        Tech = 3,
        RPG = 4,
        LOL = 5,
        PressForward = 6,
        SpeedTech = 7,
        MultiLap = 8,
        Offroad = 9,
        Trial = 10,
        ZrT = 11,
        SpeedFun = 12,
        Competitive = 13,
        Ice = 14,
        Dirt = 15,
        Stunt = 16,
        Reactor = 17,
        Platform = 18,
        SlowMotion = 19,
        Bumper = 20,
        Fragile = 21,
        Scenery = 22,
        Kacky = 23,
        Endurance = 24,
        Mini = 25,
        Remake = 26,
        Mixed = 27,
        Nascar = 28,
        SpeedDrift = 29,
        Minigame = 30,
        Obstacle = 31,
        Transitional = 32,
        Grass = 33,
        Backwards = 34,
        EngineOff = 35,
        Signature = 36,
        Royal = 37,
        Water = 38,
        Plastic = 39,
        Arena = 40,
        Freestyle = 41,
        Educational = 42,
        Sausage = 43,
        Bobsleigh = 44,
        Pathfinding = 45,
        FlagRush = 46,
        Puzzle = 47,
        Freeblocking = 48,
        AlteredNadeo = 49,
        SnowCar = 50,
        Wood = 51,
        Underwater = 52,
        Turtle = 53,
        RallyCar = 54,
        MixedCar = 55,
        Bugslide = 56,
        Mudslide = 57,
        MovingItems = 58,
        DesertCar = 59,
        SpeedMapping = 60,
        NoBrake = 61,
        CruiseControl = 62,
        NoSteer = 63,
        RPGImmersive = 64,
        Pipes = 65,
    }
}
